writer1 = console
writer2 = file
writer2.file = logs/expense-tracker.log
writer2.level = debug
writer2.format = {date: yyyy-MM-dd HH:mm:ss} [{level}] {class}.{method}() - {message}
writer2.append = false